server:
  port: 8092
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  redis:
    host: 172.16.116.100
  rabbitmq:
    host: 172.16.116.100
    virtual-host: /fengge
    username: fengge
    password: fengge
gmall:
  jwt:
    pubKeyPath: D:\\project-0722\\rsa\\rsa.pub # 公钥地址
    cookieName: GMALL_TOKEN
alipay:
  app_id: 2016101700705587
  merchant_private_key: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCy/f6ysPx8lEB94QUgkPfPyE+zzDr9HEyz7uF7zjdn/r05E6JcIxn3k0/D15oSC/cECrO7kpSLkJ2xKqUx4sU/5lmpwm7hOtgKRklpf2Q0sHNWU78vcPrUV0/I6SF1fPTtNdnx1xKt6GkEDRO+ljU+QzvyyDvvJ8odxzAX6rBKOwQBb3+69EBOwMshQ41I1w7mHV9apP7Ub09z6N/mXmg+BNQFzFL0g5jr25n/0DfaxZ89i42T4epm/m5gbbyfotmD69yOlHxUjkABMaxmZV++IKq98sCLsuL6EDFOagDPXZbvMXs0FgySgnnzax12LmTsvJL9imK5Hquj/o1ez52lAgMBAAECggEBAJR++qZ/BQnJ6PNGEv3gp2c/1TficPH6X3xL68/N1tO1WIEY0/NCv9FQ6rUcktr0CDvXMSOlyQ08rkcEjUakz2ZjEfIvt9OuAPwNMeyPXrADz7xIAG44ejBeO3gASdzyDTUbHzRvbTTQgwd0XfQZJBUCrKKQEoEn7pvj2/eLojQB+X9JiV4xeV8nLsxYc1LoYeXIZhFU89Nlq+UZMc1HZ3aXx/wDAtPJlsQk7EiKVX5kJhYMSnaK5RiFU2iw4Ey7MrZ/yVUtqTyS+7MSYsjTCPi3yW/dQi1Qr/Pg/tMUlhiQx89n03JUdv5778Q2uR4A7d4dBYSs4mkwik2PdeaAD0ECgYEA9gwV+Gc8mmQBP1kuI2agsQGzX17SxNyoA2vnQmxXxC6jzYq3WGHm37usid62FVgkMvkN+rl/8BVI1VlOtblVDWc0IH+KxlQGtKvP2CZKmkRAlIjDbO1mHUmJI0npQINlvsnBMZNbuwmabyfvryUxRZC54iChVkMgjeJwjljVvDUCgYEAujuHNNPtefwXYZ2NM41D0wNB4WPKtNYhRxffiBRaGSwDqO5DbFLeNurswxo/m9ZhYvQS+SX704Puipi1Qys8tCl5oIKWLKlv8wCtgf01ZfeuFTh7cAauTijenj1wiN03yYfQEjWWuLXEr4gIOXOqdTZIXg2be3Jgd6+Wq+zUKbECgYBU38BoarxGCb9AafP3dDx0MsD8YgpUrEUswPkKObNg0jHhAjvSuhrZDLUs7e1jmX8LMkx3M6wFVmJEbkUvfJnxQKuDllt5pJyXkDjnN/Y+FtMsKa04EwBJlAdBbAqRHYJoeNIy1sEq2No0A9OzWCIR/CWS8myVBBzjtLvc7pn0DQKBgBvteWUustosN8VnvxkQAi/OuT53nJpp0iu7JMZfZvOHajUXJf1EoBZUPJU1hnx0Nb6FI6NBUvZxPoCCTgx4m23ZGmg7rRGdhzBF1b88nZlg/zYndjtihRkrf9bzF8Eui4MpXsacSrIAcDJyj+kts05IiamxGLP2fwjzyACYT2jBAoGBAPFGW4AJHIilWmJw9wR/Kod8Rcp2PfnkDdA7y6zpBAuImn2ACJVKLk9GilO4Tl1CJixSFhkaFOvrAIg11AEDtkq5WYFV/0hzUlRlB4ov7Oq3OlGLERhRGoZujvtnY/Bxyxp+iqhulcIo9HrDehP8roXGmKUJ8EujIuVOBVhEgc5Y
  alipay_public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA1/Vh011ewdKcvnaMwzEMKRFSF1P3kfDc/+22tkxjFgODzhXFU1/zcyRW+573cVM29s1nhecEABpcKz3PmA/IRSKs8HuZhw2GNoojlXEgVNoFURmrUqeEZTiWf+xJNsV7/MjHbjHoqYbJW7OFsnuxdkCwzHXtC1tW8Od03hjLt8L4vlPneiWsIk16942mtUczbpMuaXfRQjXRJGr4eZump/VWwJeG9XZMK8ShyLL6OToWxNoygZBxYkfkV2PsVK7ha/7byD9S6f3zgrRQqteCJ0Ciclm4wgx3n3ohIx1pIHzWNfgqyM+Kl5I0u4KrdOUJrnGTtdhyA4/5D3ue9vY+WQIDAQAB
  notify_url: http://9glldacce2.52http.net/api/order/pay/success
  return_url: http://www.baidu.com
  sign_type: RSA2
  gatewayUrl: https://openapi.alipaydev.com/gateway.do